# https://nurbs-python.readthedocs.io/en/latest/

# Use RTD config version 2
version: 2

# Use RTD latest python image
build:
  image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build HTML and PDF docs
formats:
  - htmlzip
  - pdf

# Python options
python:
  version: 3.7
  install:
    - method: setuptools  # use "python setup.py install" method
      path: .  # execute command "python ./setup.py install"
  system_packages: true  # needed for numpy, matplotlib, etc.
