# conda-build recipe for NURBS-Python (geomdl) package
{% set setup_data = load_setup_py_data() %}
{% set build_number = 0 %}

package:
  name: geomdl
  version: {{ setup_data['version'] }}

source:
  path: ../../

build:
  noarch: python
  number: {{ build_number }}
  script:
    - python setup.py sdist
    - pip install dist/geomdl-{{ setup_data['version'] }}.tar.gz --no-deps

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - geomdl
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - python -c "import geomdl; print(geomdl.__version__)"
    - pytest

about:
  home: https://onurraufbingol.com/NURBS-Python/
  license: MIT
  license_family: MIT
  summary: Object-oriented B-Spline and NURBS evaluation library
  description: |
    NURBS-Python (geomdl) is an object-oriented B-Spline and NURBS library. The core
    library is pure Python code with no dependencies. Visualization modules depend on
    external Python packages, such as matplotlib, Plotly and VTK. Please refer to the
    documentation <http://nurbs-python.readthedocs.io/> for a list of features.
    Please refer to the examples repo <https://github.com/orbingol/NURBS-Python_Examples>
    for example scripts.
  doc_url: http://nurbs-python.readthedocs.io/
  dev_url: https://github.com/orbingol/NURBS-Python

extra:
  recipe-maintainers:
    - orbingol
