"""
.. module:: exchange.obj
    :platform: Unix, Windows
    :synopsis: Provides exchange capabilities for OBJ file format

.. moduleauthor:: Onur R. Bingol <contact@onurbingol.net>

"""

from . import exc_helpers
from .. import entity
from ..tessellate import triangular
from ..base import export, GeomdlError


@export
def export_obj_str(surface, **kwargs):
    """ Exports surface(s) in Wavefront OBJ format as a string.

    Keyword Arguments:
        * ``vertex_normals``: if True, computes vertex normals (``vn`` element). *Default: False*
        * ``parametric_vertices``: if True, adds parameter space vertices (``vp`` element). *Default: False*

    :param surface: input surface(s)
    :type surface: BSpline.Surface
    :return: contents of the .obj file generated
    :rtype: str
    """
    # Get keyword arguments
    include_vertex_normal = kwargs.get('vertex_normals', False)
    include_param_vertex = kwargs.get('parametric_vertices', False)

    # Input validity checking
    if surface.pdimension != 2:
        raise GeomdlError("Can only export surfaces")

    # Create the string and start adding triangulated surface points
    line = "# Generated by geomdl\n"
    vertex_offset = 0  # count the vertices to update the face numbers correctly

    # Initialize lists for geometry data
    str_v = []  # vertices
    str_vn = []  # vertex normals
    str_vp = []  # parameter space vertices
    str_f = []  # faces

    # Loop through SurfaceContainer object
    for srf in surface:
        # Tessellate surface
        vertices, triangles = triangular.make_triangle_mesh(srf.evalpts, srf.sample_size[0], srf.sample_size[1])

        # Collect vertices
        for vert in vertices:
            temp = "v " + str(vert.x) + " " + str(vert.y) + " " + str(vert.z) + "\n"
            str_v.append(temp)

        # Collect parameter space vertices
        if include_param_vertex:
            for vert in vertices:
                temp = "vp " + str(vert.uv[0]) + " " + str(vert.uv[1]) + "\n"
                str_vp.append(temp)

        # Compute vertex normals
        if include_vertex_normal:
            for vert in vertices:
                sn = exc_helpers.surface_normal(srf, vert.uv, True)
                temp = "vn " + str(sn[1][0]) + " " + str(sn[1][1]) + " " + str(sn[1][2]) + "\n"
                str_vn.append(temp)

        # Collect faces (1-indexed)
        for t in triangles:
            vl = t.data
            temp = "f " + \
                   str(vl[0] + 1 + vertex_offset) + " " + \
                   str(vl[1] + 1 + vertex_offset) + " " + \
                   str(vl[2] + 1 + vertex_offset) + "\n"
            str_f.append(temp)

        # Update vertex offset
        vertex_offset = len(str_v)

    # Write all collected data to the return string
    for lv in str_v:
        line += lv
    for lvn in str_vn:
        line += lvn
    for lvp in str_vp:
        line += lvp
    for lf in str_f:
        line += lf

    return line


def export_obj(surface, file_name, **kwargs):
    """ Exports surface(s) as a .obj file.

    Keyword Arguments:
        * ``vertex_normals``: if True, computes vertex normals (``vn`` element). *Default: False*
        * ``parametric_vertices``: if True, adds parameter space vertices (``vp`` element). *Default: False*

    :param surface: input surface(s)
    :type surface: BSpline.Surface
    :param file_name: name of the output file
    :type file_name: str
    :raises GeomdlException: an error occurred writing the file
    """
    return exc_helpers.write_file(file_name, export_obj_str(surface, **kwargs))
