# geomdl DockerFile for Python v3.6
FROM python:3.6-alpine

USER root
WORKDIR /nurbs

RUN apk add --no-cache build-base wget git freetype-dev openblas-dev bash \
    && git clone https://github.com/orbingol/NURBS-Python.git library \
    && git clone https://github.com/orbingol/NURBS-Python_Examples.git examples \
    && git clone https://github.com/orbingol/geomdl-cli.git app

WORKDIR /nurbs/library

RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir tornado \
    && python setup.py bdist_wheel --use-cython \
    && pip install dist/* \
    && python setup.py clean --all \
    && rm -rf dist/ \
    && python -c "import geomdl" \
    && python -c "import geomdl.core"

WORKDIR /nurbs/app

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir . \
    && python -c "import geomdl.cli"

WORKDIR /root

COPY matplotlibrc .config/matplotlib/matplotlibrc
COPY README.md .
RUN echo "cat README.md" >> .bashrc

ENTRYPOINT ["/bin/bash", "-i"]

EXPOSE 8000
