# geomdl DockerFile for Python v3.7
FROM python:3.7-slim

USER root
WORKDIR /nurbs

RUN apt-get update \
    && apt-get install -y gcc git \
    && apt-get clean \
    && pip install numpy matplotlib plotly pytest cython tornado \
    && git clone https://github.com/orbingol/NURBS-Python.git library \
    && git clone https://github.com/orbingol/NURBS-Python_Examples.git examples

WORKDIR /nurbs/library

RUN python setup.py develop \
    && python setup.py build_ext --use-cython --inplace \
    && python setup.py clean --all \
    && pytest \
    && python -c "import geomdl_core" \
    && useradd -ms /bin/bash nurbs \
    && chown -R nurbs:nurbs /nurbs

USER nurbs
WORKDIR /home/nurbs

COPY --chown=nurbs:nurbs matplotlibrc .config/matplotlib/matplotlibrc
COPY --chown=nurbs:nurbs README.md .

RUN echo "cat README.md" >> .bashrc

ENTRYPOINT ["/bin/bash", "-i"]

EXPOSE 8000
